package cn.edu.whu.trajspark.coding;

import cn.edu.whu.trajspark.datatypes.ByteArray;
import org.locationtech.jts.geom.LineString;
import org.locationtech.jts.geom.Polygon;

import java.io.Serializable;
import java.util.List;

/**
 * SpatialCoding is a part of the HBase row key, which only contains spatial information of the trajectories storing.
 *
 * @author Haocheng Wang
 * Created on 2022/10/4
 */
public interface SpatialCoding extends Serializable {

  /**
   * Get a spatial code for the trajectory line string.
   *
   * @param lineString Line string represents the point list of a trajectory.
   * @return The spatial coding value calculated by the implemented spatial coding strategy.
   */
  public ByteArray code(LineString lineString);


  /**
   * Get spatial polygon which is represented by the input spatial coding byte array.
   *
   * @param spatialCodingByteArray Spatial coding byte array generated by this coding strategy.
   * @return Polygon represented by the spatial coding.
   * <ul>
   *     <li>for xz2, the polygon is an enlarged range.</li>
   *     <li>for xz2p, which concat xz2 and poscode, the polygon is quad of the enlarged spatial range.</li>
   * </ul>
   */
  public Polygon getCodingPolygon(ByteArray spatialCodingByteArray);
}
